site:
  title: WAF++ Documentation
  url: https://waf2p.dev/docs
  start_page: wafpp::index.adoc

content:
  sources:
  # German content (version: de)
  - url: https://github.com/WAF2p/framework.git
    branches: main-de
  # English content (version: en) — translated pages maintained on this branch
  - url: https://github.com/WAF2p/framework.git
    branches: main-en

antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
    index_by_heading: true
    languages: [en, de]
    snippet_length: 150
  - require: '@antora/pdf-extension'

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui

asciidoc:
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
    - asciidoctor-treeview
  attributes:
    page-pagination: ''
    source-language: asciidoc@
    tabs-sync-option: ''

output:
  clean: true
  dir: ./_site/docs
