#!/usr/bin/env node
/**
 * Build-time RFC crawler for the Jekyll marketing site.
 *
 * Queries the public GitHub API for issues whose title contains "RFC"
 * across the WAF2p repos, fetches comments and unique commenters, and writes
 * _data/github_rfcs.yml consumed by the RFC tracker page.
 *
 * Run with:
 *   node scripts/fetch-rfcs.mjs
 *
 * For private repositories or higher rate limits, set GITHUB_TOKEN.
 */
import { writeFileSync } from 'node:fs'
import path from 'node:path'
import process from 'node:process'

const REPOS = [
  { owner: 'WAF2p', repo: 'framework', name: 'framework' },
  { owner: 'WAF2p', repo: 'pass', name: 'pass' },
  { owner: 'WAF2p', repo: 'wafpass-server', name: 'wafpass-server' },
  { owner: 'WAF2p', repo: 'wafpass-dashboard', name: 'wafpass-dashboard' },
  { owner: 'WAF2p', repo: 'wafpass-action', name: 'wafpass-action' },
  { owner: 'WAF2p', repo: 'wafpass-mcp', name: 'wafpass-mcp' },
]

const OUTPUT = path.resolve(process.cwd(), '_data/github_rfcs.yml')
const RFC_TITLE_RE = /\bRFC\b/i

async function ghFetch(url) {
  const headers = {
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
  }
  const token = process.env.GITHUB_TOKEN
  if (token) {
    headers.Authorization = `Bearer ${token}`
  }

  const res = await fetch(url, { headers })
  if (!res.ok) {
    throw new Error(`GitHub API error ${res.status}: ${res.statusText} (${url})`)
  }
  return res.json()
}

function inferCategory(issue, repoName) {
  const labels = (issue.labels || []).map(l => (typeof l === 'string' ? l : l.name).toLowerCase())
  if (labels.includes('documentation') || labels.includes('docs')) return 'docs'
  if (labels.includes('governance')) return 'governance'
  if (labels.includes('framework')) return 'framework'
  if (repoName === 'framework') return 'framework'
  return 'tooling'
}

function inferStatus(issue) {
  if (issue.state === 'open') return 'open'
  const labels = (issue.labels || []).map(l => (typeof l === 'string' ? l : l.name).toLowerCase())
  if (labels.includes('implemented')) return 'implemented'
  if (labels.includes('rejected')) return 'rejected'
  if (labels.includes('withdrawn')) return 'withdrawn'
  if (labels.includes('accepted')) return 'accepted'
  // Default closed RFCs to implemented; override via labels when known.
  return 'implemented'
}

function stripMarkdown(text) {
  if (!text) return ''
  return text
    .replace(/\r\n/g, '\n')
    .replace(/```[\s\S]*?```/g, '')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/#+\s+/g, '')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/!?\[([^\]]*)\]\([^)]+\)/g, '$1')
    .replace(/\*\*|__/g, '')
    .replace(/\n+/g, ' ')
    .trim()
}

function extractSummary(body, maxLength = 260) {
  const text = stripMarkdown(body || '')
  const firstPara = text.split(/\n\s*\n/)[0] || text
  const cleaned = firstPara.replace(/\s+/g, ' ').trim()
  if (cleaned.length <= maxLength) return cleaned
  const truncated = cleaned.slice(0, maxLength)
  const lastSpace = truncated.lastIndexOf(' ')
  return (lastSpace > 0 ? truncated.slice(0, lastSpace) : truncated) + '…'
}

function formatDate(iso) {
  return iso ? iso.slice(0, 10) : ''
}

function yamlString(value) {
  if (value === null || value === undefined) return 'null'
  const str = String(value)
  // Quote strings that contain colons, hashes, quotes, brackets, or leading special chars.
  const needsQuote = /[:#"'\[\]{}|>&*!,%@`]/.test(str) || /^[-?:|>&*!,%@`\s]/.test(str) || str.includes('\n')
  if (needsQuote) {
    const escaped = str.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')
    return `"${escaped}"`
  }
  return str
}

function yamlList(items, indent = '    ') {
  if (!items || items.length === 0) return ' []'
  return '\n' + items.map(item => {
    const lines = []
    lines.push(`${indent}- login: ${yamlString(item.login)}`)
    if (item.avatar_url) lines.push(`${indent}  avatar_url: ${yamlString(item.avatar_url)}`)
    if (item.html_url) lines.push(`${indent}  html_url: ${yamlString(item.html_url)}`)
    return lines.join('\n')
  }).join('\n')
}

function toYaml(rfcs) {
  const lines = [
    '# Auto-generated by scripts/fetch-rfcs.mjs',
    '# Do not edit manually — rerun the script to refresh.',
    '#',
    `# generatedAt: ${new Date().toISOString()}`,
    `# source: https://api.github.com`,
    `# repos: ${REPOS.map(r => `${r.owner}/${r.repo}`).join(', ')}`,
    '',
  ]

  for (const rfc of rfcs) {
    lines.push(`- id: ${yamlString(rfc.id)}`)
    lines.push(`  title_en: ${yamlString(rfc.title_en)}`)
    lines.push(`  title_de: ${yamlString(rfc.title_de)}`)
    lines.push(`  summary_en: ${yamlString(rfc.summary_en)}`)
    lines.push(`  summary_de: ${yamlString(rfc.summary_de)}`)
    lines.push(`  category: ${yamlString(rfc.category)}`)
    lines.push(`  status: ${yamlString(rfc.status)}`)
    lines.push(`  author: ${yamlString(rfc.author)}`)
    lines.push(`  author_avatar: ${yamlString(rfc.author_avatar)}`)
    lines.push(`  author_url: ${yamlString(rfc.author_url)}`)
    lines.push(`  opened: ${yamlString(rfc.opened)}`)
    if (rfc.decided) lines.push(`  decided: ${yamlString(rfc.decided)}`)
    if (rfc.implemented) lines.push(`  implemented: ${yamlString(rfc.implemented)}`)
    lines.push(`  discussion: ${yamlString(rfc.discussion)}`)
    lines.push(`  repo: ${yamlString(rfc.repo)}`)
    lines.push(`  issue_number: ${yamlString(rfc.issue_number)}`)
    lines.push(`  comment_count: ${yamlString(rfc.comment_count)}`)
    lines.push(`  commenters:${yamlList(rfc.commenters)}`)
    lines.push('')
  }

  return lines.join('\n')
}

async function fetchComments(issue, repoFullName) {
  if (!issue.comments) return []
  const comments = await ghFetch(
    `https://api.github.com/repos/${repoFullName}/issues/${issue.number}/comments?per_page=100`,
  )
  return comments.map(c => ({
    id: c.id,
    login: c.user?.login ?? 'unknown',
    avatar_url: c.user?.avatar_url ?? '',
    html_url: c.user?.html_url ?? '',
  }))
}

async function fetchRfcsForRepo({ owner, repo, name }) {
  const repoFullName = `${owner}/${repo}`

  let issues = []
  try {
    issues = await ghFetch(
      `https://api.github.com/repos/${repoFullName}/issues?state=all&labels=rfc&per_page=100`,
    )
  } catch (err) {
    if (process.env.DEBUG) {
      console.warn(`[warn] Could not fetch RFC-labeled issues for ${repoFullName}: ${err.message}`)
    }
  }

  let searchHits = []
  try {
    const search = await ghFetch(
      `https://api.github.com/search/issues?q=repo:${repoFullName}+RFC+in:title&type=issues&per_page=100`,
    )
    searchHits = search.items || []
  } catch (err) {
    if (process.env.DEBUG) {
      console.warn(`[warn] Could not search RFC titles for ${repoFullName}: ${err.message}`)
    }
  }

  const byNumber = new Map()
  for (const issue of issues) {
    byNumber.set(issue.number, issue)
  }
  for (const issue of searchHits) {
    if (!byNumber.has(issue.number)) {
      byNumber.set(issue.number, issue)
    }
  }

  const candidates = Array.from(byNumber.values()).filter(
    i => RFC_TITLE_RE.test(i.title) || (i.labels || []).some(l => (typeof l === 'string' ? l : l.name).toLowerCase() === 'rfc'),
  )

  const rfcs = []
  for (const issue of candidates) {
    const status = inferStatus(issue)
    const category = inferCategory(issue, name)
    const title = issue.title.replace(/\s*\(RFC\)\s*/i, ' ').replace(/\s+/g, ' ').trim()
    const summary = extractSummary(issue.body)

    const comments = await fetchComments(issue, repoFullName)
    const seen = new Map()
    for (const c of comments) {
      if (!seen.has(c.login)) {
        seen.set(c.login, c)
      }
    }
    const commenters = Array.from(seen.values())

    rfcs.push({
      id: `GH-${name}-${issue.number}`,
      title_en: title,
      title_de: title,
      summary_en: summary,
      summary_de: summary,
      category,
      status,
      author: issue.user?.login ?? 'unknown',
      author_avatar: issue.user?.avatar_url ?? '',
      author_url: issue.user?.html_url ?? '',
      opened: formatDate(issue.created_at),
      decided: status !== 'open' && issue.closed_at ? formatDate(issue.closed_at) : undefined,
      implemented: status === 'implemented' && issue.closed_at ? formatDate(issue.closed_at) : undefined,
      discussion: issue.html_url,
      repo: name,
      issue_number: issue.number,
      comment_count: comments.length,
      commenters,
    })
  }

  return rfcs
}

async function main() {
  const allRfcs = []
  for (const repo of REPOS) {
    const rfcs = await fetchRfcsForRepo(repo)
    if (process.env.DEBUG) {
      console.log(`[debug] ${repo.owner}/${repo.repo}: ${rfcs.length} RFC(s)`)
    }
    allRfcs.push(...rfcs)
  }

  allRfcs.sort((a, b) => new Date(b.opened).getTime() - new Date(a.opened).getTime())

  writeFileSync(OUTPUT, toYaml(allRfcs))
  console.log(`Wrote ${allRfcs.length} live GitHub RFC(s) to ${OUTPUT}`)
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
